baseURL = 'https://kalmai.github.io/portfolio/'
languageCode = 'en-us'
title = 'kalmai'
theme = ['hugo-shortcode-roneo-button-icon-badge', 'risotto']
copyright = "© [kalmai](https://kalmai.github.io/portfolio/)"

paginate = 3
DefaultContentLanguage = "en"
enableInlineShortcodes = true

# Automatically add content sections to main menu
sectionPagesMenu = "main"

[params]
noindex = false

[languages]
  # https://gohugo.io/methods/page/alltranslations/
  [languages.en]
    contentDir = 'content'
    languageCode = 'en-US'
    languageName = 'english'
    weight = 1

[params.resume]
# located in ./static/
file = "portfolio/ZacharyKolker_SoftwareDeveloper.pdf"

[params.theme]
palette = "base16-dark"

# Sidebar: about/bio
[params.about]
title = "zachary kolker"
description = "ruby programming language enjoyer"
# unicode/emoji logo:
logo = "飛騨"
# or use an image:
# logo_image = "image/location.png"

# Sidebar: social links
# Available icon sets:
# * FontAwesome 6 <https://fontawesome.com/> ('fa-brands', 'fa-normal', or 'fa-solid' for brands)
# * Academicons <https://jpswalsh.github.io/academicons> ('ai ai-')

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "github"
url = "https://github.com/kalmai"

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "email"
url = "mailto:zacharykolker93@gmail.com"

[[params.socialLinks]]
icon = "fa-brands fa-linkedin"
title = "linkedin"
url = "https://www.linkedin.com/in/zachary-kolker"


[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true

[markup]

  # Table of contents
  # Add toc = true to content front matter to enable
  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = true
